version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1.2
  shellcheck: circleci/shellcheck@3.1
  rust: circleci/rust@1.6.0

executors:
  linux:
    parameters:
      image:
        description: The image to use for the executor.
        type: string
        default: cimg/base:stable
    docker:
      - image: << parameters.image >>
  linux-machine: &linux-machine
    machine:
      image: ubuntu-2004:202101-01
  macos: &macos
    macos:
      xcode: 13.3.0

workflows:
  lint-pack:
    jobs:
      - test-scripts:
          matrix:
            parameters:
              os: [linux-machine, macos]
          filters:
            tags:
              only: /.*/
              ignore: binary-dev
      - build-scripts:
          matrix:
            parameters:
              os: [linux-machine, macos]
          filters:
            tags:
              only: /.*/
              ignore: binary-dev
          requires: [test-scripts]
      - release-binaries:
          filters:
            tags:
              only: /.*/
              ignore: binary-dev
          context: orb-publishing
          requires: [build-scripts]
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
              ignore: binary-dev
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
              ignore: binary-dev
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
              ignore: binary-dev
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
      - orb-tools/publish:
          orb-name: eld/nix
          requires:
            [
              release-binaries,
              orb-tools/lint,
              orb-tools/review,
              orb-tools/pack,
              shellcheck/check,
            ]
          vcs-type: << pipeline.project.type >>
          # Use a context to hold your publishing token.
          context: orb-publishing
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]

jobs:
  test-scripts:
    parameters:
      os:
        description: "executor to run the job against"
        type: executor
        default: linux
    executor: << parameters.os >>
    steps:
      - checkout
      - rust/install
      - rust/test:
          with_cache: false

  build-scripts:
    parameters:
      os:
        description: "executor to run the job against"
        type: executor
        default: linux
    executor: << parameters.os >>
    steps:
      - checkout
      - rust/install
      - when:
          condition:
            or:
            - equal: [*linux-machine, << parameters.os >>]
          steps:
            - run:
                name: "Add Linux musl target and required build tools"
                command: |
                  rustup target add x86_64-unknown-linux-musl
                  sudo apt-get install -y musl-tools
            - run:
                name: "Build for musl (static binary)"
                command: cargo build --release --target=x86_64-unknown-linux-musl
            - run:
                name: "Copy built binary to workspace"
                command: |
                  mkdir -p ~/dist/linux-musl
                  cp target/x86_64-unknown-linux-musl/release/install-nix ~/dist/linux-musl/install-nix
            - persist_to_workspace:
                root: ~/dist
                paths:
                  - linux-musl
      - when:
          condition:
            or:
            - equal: [*macos, << parameters.os >>]
          steps:
            - rust/build:
                release: true
                with_cache: false
            - run:
                name: "Copy built binary to workspace"
                command: |
                  mkdir -p ~/dist/darwin
                  cp target/release/install-nix ~/dist/darwin/install-nix
            - persist_to_workspace:
                root: ~/dist
                paths:
                  - darwin

  release-binaries:
    executor:
      name: linux
      image: cimg/go:1.16
    steps:
      - checkout
      - attach_workspace:
          at: ./dist
      - run:
          name: "Create a tag"
          command: |
            git push origin :refs/tags/binary-dev
            git tag -f binary-dev
            git push origin main --tags
      - run:
          name: "Release binaries to GitHub"
          command: |
            ls -al
            go get -u github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace -prerelease binary-dev ./dist
