version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0.2

executors:
  linux:
    parameters:
      image:
        description: The image to use for the executor.
        type: string
        default: cimg/base:stable
    docker:
      - image: << parameters.image >>
  linux-machine:
    machine:
      image: ubuntu-2204:current
  macos: &macos
    macos:
      xcode: 14.2.0

workflows:
  test-pack:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb_name: eld/nix
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
          vcs_type: << pipeline.project.type >>
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters:
            tags:
              only: /.*/
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          orb_name: eld/nix
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters:
            tags:
              only: /.*/
