version: 2.1
orbs:
  cachix: eld/nix@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

executors:
  linux:
    parameters:
      image:
        description: The image to use for the executor.
        type: string
        default: cimg/base:stable
    docker:
      - image: << parameters.image >>
  linux-machine:
    machine:
      image: ubuntu-2004:202101-01
  macos:
    macos:
      xcode: 13.3.0

workflows:
  test-deploy:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
      - test-nix-install:
          matrix:
            parameters:
              os: [linux, linux-machine, macos]
          filters:
            tags:
              only: /.*/
      - upload-release-binaries:
          requires:
            - test-nix-install
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: orb-publishing
      - orb-tools/publish:
          orb-name: eld/nix
          requires:
            - upload-release-binaries
          context: orb-publishing
          vcs-type: << pipeline.project.type >>
          pub-type: production
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  test-nix-install:
    parameters:
      os:
        description: "Which executor to run on"
        type: executor
        default: linux-machine
    executor: << parameters.os >>
    steps:
      - checkout
      - nix/install:
          binary_tag: binary-dev
      - run:
          name: "Test nix install"
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install

  upload-release-binaries:
    executor:
      name: linux
      image: cimg/go:1.16
    steps:
      - checkout
      - attach_workspace:
          at: ./dist
      - run:
          name: "Release binaries to GitHub"
          command: |
            ls -al
            go get -u github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace -delete -prerelease ${CIRCLE_TAG} ./dist

