version: 2.1
orbs:
  cachix: eld/nix@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

workflows:
  test-deploy:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb-name: eld/cachix
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
          context: orb-publishing
          vcs-type: << pipeline.project.type >>
          pub-type: production
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

