version: 2.1
orbs:
  nix: eld/nix@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.6.1

executors:
  linux:
    parameters:
      image:
        description: The image to use for the executor.
        type: string
        default: cimg/base:stable
    docker:
      - image: << parameters.image >>
  linux-machine:
    machine:
      image: ubuntu-2004:202101-01
  macos:
    macos:
      xcode: 14.2.0

workflows:
  test-deploy:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
          requires:
            - test-nix-install
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
          requires:
            - test-nix-install
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
          requires:
            - test-nix-install
      - test-nix-install:
          matrix:
            parameters:
              os: [linux-machine, macos]
          filters:
            tags:
              only: /.*/
          context: nix
      - orb-tools/publish:
          orb-name: eld/nix
          requires:
            - test-nix-install
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
          context: orb-publishing
          vcs-type: << pipeline.project.type >>
          pub-type: production
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  test-nix-install:
    parameters:
      os:
        description: "Which executor to run on"
        type: executor
        default: linux-machine
    executor: << parameters.os >>
    steps:
      - checkout
      - nix/install
      - nix/install-cachix
      - nix/with-cachix:
          cachix-user: eld
          nix-command: nix profile install nixpkgs#cowsay.out
      - run:
          name: Cowsay command
          command: cowsay "Hello, nix-orb!"
