description: >
  This is a Docker executor using the official nixpkgs/nix Docker image.
  You should use this executor if you want to use Nix in Docker as it's tricky
  to install otherwise.

  Note: The `nix/install` command is not necessary when using this executor.
docker:
  - image: 'nixpkgs/nix:<<parameters.tag>>'
parameters:
  tag:
    default: nixos-21.11
    description: >
      Pick a specific nixpkgs/nix image variant:
      https://hub.docker.com/r/nixpkgs/nix/tags
    type: string
